-- Tabela de prospecção (editável pelo painel: admin/gestor adicionam e mudam status).
-- Rode DEPOIS do schema.sql. O seed (lojas reais) é adicionado ao final deste arquivo.
create table if not exists public.prospeccao (
  id bigint generated always as identity primary key,
  loja text not null,
  cidade text,
  regiao text,
  tipo text,
  status text not null default 'a-contatar',
  contato text,
  obs text,
  criado_em timestamptz default now()
);
alter table public.prospeccao enable row level security;

drop policy if exists sel on public.prospeccao;
create policy sel on public.prospeccao for select
  using (public.meu_papel() in ('admin','gestor'));

drop policy if exists ins on public.prospeccao;
create policy ins on public.prospeccao for insert to authenticated
  with check (public.meu_papel() in ('admin','gestor'));

drop policy if exists upd on public.prospeccao;
create policy upd on public.prospeccao for update
  using (public.meu_papel() in ('admin','gestor'))
  with check (public.meu_papel() in ('admin','gestor'));

drop policy if exists del on public.prospeccao;
create policy del on public.prospeccao for delete
  using (public.meu_papel() in ('admin','gestor'));

delete from public.prospeccao;
insert into public.prospeccao (loja,cidade,regiao,tipo,status) values
  ('Casa de Carne do Gringo','Cruz Alta','Noroeste do RS','Açougue','a-contatar'),
  ('Casa de Carnes Ivaí','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Casa de Carnes e Mercado Serrana','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Churrascaria Wagner','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Conveniência 2001','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Conveniência da Barão','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Drum Super','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Irmãos Linke e Cia','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Loja Alternativa','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado e Comércio de Rações Maldaner','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Minimercado Azevedo','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Pães e Massas','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Sadia Alimentos','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Marangon','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Útil da Lomba','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Amaral','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Daltrozo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Linassi','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Pag Pouco','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Super Útil','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Super Útil - Domingos Verissimo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Zaffari','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Zaffari Erico Verissimo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Telê Mercado e Açougue','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Walmart - Nacional','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Comercial Zaffari','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotripal','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Loja do Darci','Ijuí','Noroeste do RS','Mercado','a-contatar'),
  ('MD Hortifruti','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Cotrijuí','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Nacional','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Kuchak','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('UFA mercado 24h','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('mercado e açougue Martins','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotrijal','Não-Me-Toque','Noroeste do RS','Cooperativa','a-contatar'),
  ('Coopermil','Santa Rosa','Noroeste do RS','Cooperativa','a-contatar'),
  ('Açougue Gurizinho','Santo Ângelo','Noroeste do RS','Açougue','a-contatar'),
  ('Becker Supermercado','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Casa de Carnes Costelão','Santo Ângelo','Noroeste do RS','Açougue','a-contatar'),
  ('Casa do Frango','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Fruteira Missões','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Fruteira Sandayas','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Avenida','Santo Ângelo','Noroeste do RS','Mercado','ja-cliente'),
  ('Mercado Bueno','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Milanesi','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Paineira','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Nacional','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Rede Vivo','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Stock Center','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Master','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Amigão','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Caryone','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cripy','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Mattana','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Popular','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Weinert','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('UNI Mini Mercado','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Weinert Supermercados','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Ala Supermercado','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Atacadão','Chapecó','Oeste de SC','Atacado','a-contatar'),
  ('Auto Posto De Marco','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Açougue Carne Fresca','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Açougue Efapi','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Bigolin Supermercado','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Brasão','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Brasão Avenida','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Supercenter','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Superitália','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Supernorte','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Chapecó Casa de Carne','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Grupo Passarela','Chapecó','Oeste de SC','Rede','a-contatar'),
  ('Grupo Superviza','Chapecó','Oeste de SC','Rede','a-contatar'),
  ('Império Das Carnes','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Liédi Decor','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Lussisa Ferrarini Industria e Comércio de Carnes','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado Antonini','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Barp','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Economia','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Gaúcho','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Ide','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado João 23','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Karlei','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Líder','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Maravilha','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Novo Horizonte','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Novo Sul','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Rodrigues','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Sapiranga','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Vederti','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado e Açougue Gabriel','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado e Açougue LC','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado e Açougue Rossi','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado e Padaria Altas Horas','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Merco Express Belvedere','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Merco Express General','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Merco Express Presidente','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Milliuma Preço Baixo','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Moura Super Efapi','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Posto Bauer','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Posto Galli','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Royal Presidente Médici','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Maravilha','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Moura','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Moura Jardim do Lago','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Superalfa','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Annaleo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Caipirão','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Cristo Rei','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Favaretto','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Ideal','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Mercosul','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Popiolski','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Rigo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Tozzo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Tres','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Via Atacadista','Chapecó','Oeste de SC','Atacado','a-contatar'),
  ('Koch Supermercados','Concórdia','Oeste de SC','Rede','a-contatar'),
  ('Bonno Atacado e Varejo','São Miguel do Oeste','Oeste de SC','Atacado','a-contatar'),
  ('Marcon','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Confiança','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Cuca','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Gongo','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Posto MaxSul','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('SMO834','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super Marcon SMO','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super Treviso','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super fora de hora','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Superalfa','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Coração','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Paraty','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Tio Roque Atacarejo','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar');
