-- Tabela de prospecção (editável pelo painel: admin/gestor adicionam e mudam status).
-- Rode DEPOIS do schema.sql. O seed (lojas reais) é adicionado ao final deste arquivo.
create table if not exists public.prospeccao (
  id bigint generated always as identity primary key,
  loja text not null,
  cidade text,
  regiao text,
  tipo text,
  status text not null default 'a-contatar',
  contato text,
  obs text,
  criado_em timestamptz default now()
);
alter table public.prospeccao enable row level security;

drop policy if exists sel on public.prospeccao;
create policy sel on public.prospeccao for select
  using (public.meu_papel() in ('admin','gestor'));

drop policy if exists ins on public.prospeccao;
create policy ins on public.prospeccao for insert to authenticated
  with check (public.meu_papel() in ('admin','gestor'));

drop policy if exists upd on public.prospeccao;
create policy upd on public.prospeccao for update
  using (public.meu_papel() in ('admin','gestor'))
  with check (public.meu_papel() in ('admin','gestor'));

drop policy if exists del on public.prospeccao;
create policy del on public.prospeccao for delete
  using (public.meu_papel() in ('admin','gestor'));

delete from public.prospeccao;
insert into public.prospeccao (loja,cidade,regiao,tipo,status) values
  ('Boa Vista Supermercados','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Boa Vista Supermercados (Fechado)','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Casa do Pão','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Coqueiros Supermercado','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('E-Atacarejo','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Economia','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('HIPER BOA VISTA','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Hiper Boa Vista Supermercados','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Ipiranga','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado PSM','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado do Milico','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado do trabalhador','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('SUPERMERCADO COQUEIROS','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('SUPERMERCADO ECONOMIA','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('SuperEconomia Borghetti','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Boa Vista','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercados Coqueiros','Carazinho','Noroeste do RS','Supermercado','a-contatar'),
  ('Abatedouro e Açougue Lunkes','Cerro Largo','Noroeste do RS','Açougue','a-contatar'),
  ('Açougue München','Cerro Largo','Noroeste do RS','Açougue','a-contatar'),
  ('BR','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercadinho  do Pedro Gallas','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Caetano','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Compre Bem','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Kaytano','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado e Padaria Kazarão','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado Jaeschke','Cerro Largo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Jaeschke - Moinho','Cerro Largo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Strieder','Cerro Largo','Noroeste do RS','Supermercado','ja-cliente'),
  ('Supermercado São Roque','Cerro Largo','Noroeste do RS','Supermercado','a-contatar'),
  ('ampm','Cerro Largo','Noroeste do RS','Mercado','a-contatar'),
  ('Casa de Carne do Gringo','Cruz Alta','Noroeste do RS','Açougue','a-contatar'),
  ('Casa de Carnes Ivaí','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Casa de Carnes e Mercado Serrana','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Churrascaria Wagner','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Conveniência 2001','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Conveniência da Barão','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Drum Super','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Irmãos Linke e Cia','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Loja Alternativa','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado e Comércio de Rações Maldaner','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Minimercado Azevedo','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Pães e Massas','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Sadia Alimentos','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Marangon','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Útil da Lomba','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Amaral','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Daltrozo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Linassi','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Pag Pouco','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Super Útil','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Super Útil - Domingos Verissimo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Zaffari','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Zaffari Erico Verissimo','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Telê Mercado e Açougue','Cruz Alta','Noroeste do RS','Mercado','a-contatar'),
  ('Walmart - Nacional','Cruz Alta','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Ediles','Frederico Westphalen','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Longo','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercador Jardel','Frederico Westphalen','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado Barril','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Bertoletti','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cotrifred','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Pereto','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Silva','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Sorriso - Filial','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Sorriso - Matriz','Frederico Westphalen','Noroeste do RS','Supermercado','a-contatar'),
  ('Comercial Zaffari','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotripal','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Loja do Darci','Ijuí','Noroeste do RS','Mercado','a-contatar'),
  ('MD Hortifruti','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Cotrijuí','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Nacional','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Kuchak','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('UFA mercado 24h','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('mercado e açougue Martins','Ijuí','Noroeste do RS','Supermercado','a-contatar'),
  ('Atacado Cotrijal','Não-Me-Toque','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotrijal','Não-Me-Toque','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado do Juca','Não-Me-Toque','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado Casa do Pão','Não-Me-Toque','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cotrijal','Não-Me-Toque','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotrisal','Palmeira das Missões','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Calgaro','Palmeira das Missões','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado do baixinho','Palmeira das Missões','Noroeste do RS','Supermercado','a-contatar'),
  ('Cotripal','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Lojas Cotripal','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Samambaia','Panambi','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Weidle','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado do Morro','Panambi','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado Cotripal','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cotripal - Arco Íris','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cotripal - Centro','Panambi','Noroeste do RS','Supermercado','a-contatar'),
  ('Cooperativa Tritícola Santa Rosa (Cotrirosa)','Santa Rosa','Noroeste do RS','Cooperativa','a-contatar'),
  ('Coopermil','Santa Rosa','Noroeste do RS','Cooperativa','a-contatar'),
  ('Açougue Gurizinho','Santo Ângelo','Noroeste do RS','Açougue','a-contatar'),
  ('Becker Supermercado','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Casa de Carnes Costelão','Santo Ângelo','Noroeste do RS','Açougue','a-contatar'),
  ('Casa do Frango','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Fruteira Missões','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Fruteira Sandayas','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado Avenida','Santo Ângelo','Noroeste do RS','Mercado','ja-cliente'),
  ('Mercado Bueno','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Milanesi','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Paineira','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Nacional','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Rede Vivo','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Stock Center','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Super Master','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Amigão','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Caryone','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Cripy','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Mattana','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Popular','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Weinert','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('UNI Mini Mercado','Santo Ângelo','Noroeste do RS','Mercado','a-contatar'),
  ('Weinert Supermercados','Santo Ângelo','Noroeste do RS','Supermercado','a-contatar'),
  ('Açougue Ouro Verde','São Luiz Gonzaga','Noroeste do RS','Açougue','a-contatar'),
  ('Coopatrigo','São Luiz Gonzaga','Noroeste do RS','Supermercado','a-contatar'),
  ('Feron Supermercados (Centro)','São Luiz Gonzaga','Noroeste do RS','Supermercado','a-contatar'),
  ('Feron Supermercados - Centro','São Luiz Gonzaga','Noroeste do RS','Supermercado','a-contatar'),
  ('Rede Vivo','São Luiz Gonzaga','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Q Útil','São Luiz Gonzaga','Noroeste do RS','Supermercado','a-contatar'),
  ('Capelari & Cia','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('DONA ANA CARBONI','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Freese','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Garibom','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado do Povo','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Moleta','Tenente Portela','Noroeste do RS','Mercado','a-contatar'),
  ('O Colono','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Popular','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Safra','Tenente Portela','Noroeste do RS','Supermercado','a-contatar'),
  ('Mercado HI','Três de Maio','Noroeste do RS','Mercado','a-contatar'),
  ('Mercado Paulus','Três de Maio','Noroeste do RS','Mercado','a-contatar'),
  ('Supermercado Benedetti','Três de Maio','Noroeste do RS','Supermercado','a-contatar'),
  ('Supermercado Tem-Tem','Três de Maio','Noroeste do RS','Supermercado','a-contatar'),
  ('Ala Supermercado','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Atacadão','Chapecó','Oeste de SC','Atacado','a-contatar'),
  ('Auto Posto De Marco','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Açougue Carne Fresca','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Açougue Efapi','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Bigolin Supermercado','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Brasão','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Brasão Avenida','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Supercenter','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Superitália','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Celeiro Supernorte','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Chapecó Casa de Carne','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Grupo Passarela','Chapecó','Oeste de SC','Rede','a-contatar'),
  ('Grupo Superviza','Chapecó','Oeste de SC','Rede','a-contatar'),
  ('Império Das Carnes','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Liédi Decor','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Lussisa Ferrarini Industria e Comércio de Carnes','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado Antonini','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Barp','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Economia','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Gaúcho','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Ide','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado João 23','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Karlei','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Líder','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Maravilha','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Novo Horizonte','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Novo Sul','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Rodrigues','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Sapiranga','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Vederti','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Mercado e Açougue Gabriel','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado e Açougue LC','Chapecó','Oeste de SC','Açougue','a-contatar'),
  ('Mercado e Açougue Rossi','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado e Padaria Altas Horas','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Merco Express Belvedere','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Merco Express General','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Merco Express Presidente','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Milliuma Preço Baixo','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Moura Super Efapi','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Posto Bauer','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Posto Galli','Chapecó','Oeste de SC','Mercado','a-contatar'),
  ('Royal Presidente Médici','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Maravilha','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Moura','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Super Moura Jardim do Lago','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Superalfa','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Annaleo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Caipirão','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Cristo Rei','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Favaretto','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Ideal','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Mercosul','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Popiolski','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Rigo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Tozzo','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Tres','Chapecó','Oeste de SC','Supermercado','a-contatar'),
  ('Via Atacadista','Chapecó','Oeste de SC','Atacado','a-contatar'),
  ('Caitá Supermercados','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Catá Supermercados','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Copérdia','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Koch Supermercados','Concórdia','Oeste de SC','Rede','a-contatar'),
  ('Mercado Faresin','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Passarela Center','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Imperial','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Passarela','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Zat Supermercado','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('Zat Supermercados','Concórdia','Oeste de SC','Supermercado','a-contatar'),
  ('SuperAlfa - Supermercado','Coronel Freitas','Oeste de SC','Supermercado','a-contatar'),
  ('Acácia Supermercados','Descanso','Oeste de SC','Supermercado','a-contatar'),
  ('Cooper A1','Descanso','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Comin','Descanso','Oeste de SC','Supermercado','a-contatar'),
  ('Cooper A1','Itapiranga','Oeste de SC','Supermercado','a-contatar'),
  ('Guisa','Itapiranga','Oeste de SC','Supermercado','a-contatar'),
  ('Amauri Supermercado','Maravilha','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Bom Gosto','Maravilha','Oeste de SC','Mercado','a-contatar'),
  ('Rede Iguatemi Supermercados','Maravilha','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Super Centro','Maravilha','Oeste de SC','Supermercado','a-contatar'),
  ('Cooper A1','Mondaí','Oeste de SC','Supermercado','a-contatar'),
  ('Abastecedor El Jardín','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Alok2 Mart','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Carnexpress','Palmitos','Oeste de SC','Açougue','a-contatar'),
  ('Cooper A1','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Santa Lúcia','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado e Restaurante Orsolin','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Mini Súper Papiros','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Mini Súper Ruta 1','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Mini Súper y Licorera J y D','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Mini Súper y Licores El Centro','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Pulpería El Colegio','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Pulpería La Conchita','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Pulpería La Villa','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Supermercado Meotti','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Pouco Preço','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Súper Coopro Palmitos','Palmitos','Oeste de SC','Mercado','a-contatar'),
  ('Unidão Comércio em Geral','Palmitos','Oeste de SC','Supermercado','a-contatar'),
  ('Posto Delta','Pinhalzinho','Oeste de SC','Mercado','a-contatar'),
  ('Shop Estok Atacadista','Pinhalzinho','Oeste de SC','Atacado','a-contatar'),
  ('Supermercado Itaipú','Pinhalzinho','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Shimoda','Pinhalzinho','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado União','Pinhalzinho','Oeste de SC','Supermercado','a-contatar'),
  ('Ítalo Supermercado','Pinhalzinho','Oeste de SC','Supermercado','a-contatar'),
  ('Super Alfa','Quilombo','Oeste de SC','Supermercado','a-contatar'),
  ('Tartari','Seara','Oeste de SC','Supermercado','a-contatar'),
  ('Alfa - Supermercado','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Amauri Supermercado','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Deon Supermercado','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Italo Supermercado','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Prolar','São Lourenço do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Steffens','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Tito','São Lourenço do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Supermercado Alfa','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Caslo','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado São Francisco','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Verona Supermercado','São Lourenço do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Bonno Atacado e Varejo','São Miguel do Oeste','Oeste de SC','Atacado','a-contatar'),
  ('Marcon','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Confiança','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Cuca','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Gongo','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Posto MaxSul','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('SMO834','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super Marcon SMO','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super Treviso','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Super fora de hora','São Miguel do Oeste','Oeste de SC','Mercado','a-contatar'),
  ('Superalfa','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Coração','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Paraty','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('Tio Roque Atacarejo','São Miguel do Oeste','Oeste de SC','Supermercado','a-contatar'),
  ('HiperBadotti','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Marció','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Badotti Center','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Mercado Dill','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Jack','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Toígo','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Mercado Vitória','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Mercearia Lopes','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Mini Mercado Tacca','Xanxerê','Oeste de SC','Mercado','a-contatar'),
  ('Super Gentil Victoria','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Máximo','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Oeste','Xanxerê','Oeste de SC','Supermercado','a-contatar'),
  ('Brasão','Xaxim','Oeste de SC','Supermercado','a-contatar'),
  ('SUPERMERCADO ZANELLA','Xaxim','Oeste de SC','Supermercado','a-contatar'),
  ('Superalfa','Xaxim','Oeste de SC','Supermercado','a-contatar'),
  ('Supermercado Santa Marta','Xaxim','Oeste de SC','Supermercado','a-contatar');
